Remove "5.6.2" from Travis configuration.
Because travis reports:

        ERROR: The installation "5.6.2" is unknown.

... and then switches to perl-5.14.2.

Signed-off-by: James E Keenan <jkeenan@cpan.org>